---
services:
  todo-list-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  todo-list-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    # ports:
    #   - "8001:8001"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - DB_HOST=todo-list-postgres
    depends_on:
      - todo-list-postgres
  todo-list-postgres:
    image: postgres:17.1
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: